"""
IM SELFISH IMPATIENT AND A LITTLE INSECURE I MISTAKES I AM OUT OF CONTROL
ANDAT TIMES HARD TO HANDLE BUT IF YOU CANT HANDLE ME AT MY WORST THEN YOU SURE AS
HELLDONT DESERVE ME AT MY BEST MARILYN MONROE
"""